# Generated by Django 5.2.7 on 2026-06-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/'),
        ),
        migrations.AddField(
            model_name='fleet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fleet/'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
